### ISSUE TITLE
returnNamesExtraColumns returns logfile but it has not been change

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_BIDS#130]
can it be deleted from the outputs?

**Comment by CerenB** [comment]
sure? I remember that I might be using it in my logfile since I need quite a lot of columns.

**Comment by marcobarilari** [comment]
this is the code, I might be wrong but it seems that logfile is not affected by it

```matlab
% (C) Copyright 2020 CPP_BIDS developers

function [namesExtraColumns, logFile] = returnNamesExtraColumns(logFile)
    % [namesExtraColumns, logFile] = returnNamesExtraColumns(logFile)
    %

    namesExtraColumns = [];

    if isfield(logFile, 'extraColumns') && ~isempty(logFile(1).extraColumns)
        namesExtraColumns = fieldnames(logFile(1).extraColumns);
    end

end
```

**Comment by marcobarilari** [comment]
so my point is to delete logfile from the output of the function

**Comment by Remi-Gau** [comment]
I agree the logFile variable is unchanged in this function. Having it in the output is confusing because it makes the user think that the code does something to it.

I think it makes sense to delete it but we need to make that this output argument does not appear in any place in the code base where we call `returnNamesExtraColumns`.

A quick check: this appears to be the case in `saveEventsFile` (Line 194) so just make sure to changes it there.

**Comment by marcobarilari** [comment]
ok! I will probably do it in a separate pr out the dockhaton so we keep things clear, LMK

**Comment by Remi-Gau** [comment]
Well you can open a PR and mention that it is related to another [DOC] PR. I am OK to have them opened at the same time as long as we know what relates to what. :-)
